/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class socket_SocketConnection */

#ifndef _Included_socket_SocketConnection
#define _Included_socket_SocketConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     socket_SocketConnection
 * Method:    sendMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_socket_SocketConnection_sendMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
